# Generated by Django 4.2.6 on 2023-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classschedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=18)),
                ('classroom_number', models.IntegerField(default=2)),
            ],
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='date',
            field=models.DateField(default=8.242664029014178e-05),
        ),
    ]
