# Generated by Django 4.2.6 on 2023-10-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classschedule', '0002_personaldata_alter_classschedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classschedule.personaldata'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='age',
            field=models.IntegerField(),
        ),
    ]
