# Generated by Django 4.2.6 on 2023-10-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classschedule', '0003_classschedule_classroom_alter_classschedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='recording_number',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='classroom_number',
            field=models.IntegerField(default=3),
        ),
    ]
